#!/bin/sh

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width          4
bspc config window_gap            8
bspc config split_ratio           0.50
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true

BLACK="#101010"

#
# Protesilaos' colours
# https://gitlab.com/protesilaos/dotfiles/blob/master/bspwm/.config/bspwm/bspwmrc
#

#bspc config normal_border_color   "#312e30"
#bspc config active_border_color   "#b1942b"
#bspc config focused_border_color  "#6da280"
#bspc config presel_feedback_color "#2a2829"

bspc config normal_border_color   "$BLACK"
bspc config focused_border_color  "$BLACK"
bspc config urgent_border_color   "$BLACK"
bspc config presel_feedback_color "$BLACK"


###############
## autostart ##
###############

# keybinding daemon
sxhkd &

# emacs daemon
emacs --no-window-system --daemon
