[greeter]
background = /usr/share/backgrounds/leonidas-1-noon.jpg
theme-name = Adwaita
font-name = Sans 11
indicators = ~host;~spacer;~clock;~spacer;~session;~language;~a11y;~power;
clock-format = %a %b %d, %I:%M %p
user-background = false
hide-user-image = true

