#!/bin/bash
#
# Copyright (c) 2013, Thiago Farina
#
# 2013-07-13 Thiago Farina <tfarina@chromium.org>
#
# Die if any command dies.
set -e

NUM_JOBS="$(grep -c "^processor" /proc/cpuinfo)"

# Default target is chrome.
TARGET=chrome

if [ "$1" != "" ]; then
  TARGET=$1
fi

time ninja -C out_aura/Debug -k4 -j"${NUM_JOBS}" "${TARGET}" 2>&1 | tee errors
